### ISSUE TITLE
Feature Request / Suggestion - Layout Control Reset (restores defaults)

### ISSUE THREAD

**Issue by theperfectwill** [RadoslavGeorgiev/ultimate-fields#10]
Hi. So I came up with this, I think would be pretty well. Thoughts?

There is a need for a reset in the panels. I think this could be done in conjunction with the Layout Control Field. And also just a Reset button as mentioned (I think) in the Admin Pages near the "Save" button.

Here is my the idea from in using the Layout Control field. Thoughts?

![image](https://user-images.githubusercontent.com/6123260/40697485-65164892-6398-11e8-95a8-76da6f69e20c.png)

To... upon which clicking the "Reset" icon it would clear all options entered of that `layout_control` field and load any defaults if any are supplied for that controlled field.

![image](https://user-images.githubusercontent.com/6123260/40697506-7e509eb6-6398-11e8-934a-f23b7d726d32.png)

**Comment by theperfectwill** [comment]
By the way, the implementation of this is PERFECT. I mean the Layout Control option itself. Very VERY savvy.

Also, I would add this myself and do a push, but I haven't played with JS enough yet to really work that. Perhaps if you add it, I will look at the JS then to understand what was really done. JS is on my list of classes to take, skills to add.

So for now, I just hardcoded it in the div itself in `layout-control.php` under `.layout-control__load-reset`. The icon class is `dashicons-image-rotate`.

![image](https://user-images.githubusercontent.com/6123260/40697765-cf8879d8-6399-11e8-957f-5e17ab798afe.png)

You can see the css  as well...

```css
.layout-control__load-reset a.uf-button.button-primary span {
    margin: 6px 0px 0px 0px;
    font-size: 15px;
}

.layout-control__load-reset a.uf-button.button-primary {
    padding: 0px 5px 0px 5px;
}
```
