### ISSUE TITLE
Pro Issue: Color picker shows behind columns (z-index issues)

### ISSUE THREAD

**Issue by theperfectwill** [RadoslavGeorgiev/ultimate-fields#17]
Hi!

See issue screenshot below...

![image](https://user-images.githubusercontent.com/6123260/44127198-3f61064c-a00a-11e8-99fb-0a55a74aa540.png)

I just added a z-index on the fly...

```css
.uf-field.uf-field-layout-grid.uf-field-type-color {
    z-index: 9;
}
```

See result below...

![image](https://user-images.githubusercontent.com/6123260/44127386-12ba41fc-a00b-11e8-83e4-fed29b20de32.png)
